# mkdir -p $DOCKER_CONFIG/cli-plugins
- name: Create ~/.docker/cli-plugins directory
  ansible.builtin.file:
    path: "{{ ansible_user_name }}/.docker/cli-plugins"
    state: directory
    mode: '0755'

# curl -SL https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
- name: Download Docker Compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/v2.33.1/docker-compose-linux-x86_64
    dest: "{{ ansible_user_name }}/.docker/cli-plugins/docker-compose"
    mode: '0755' # chmod +x ~/.docker/cli-plugins/docker-compose

# docker compose version
- name: Verify Docker Compose installation
  command: "{{ ansible_user_name }}/.docker/cli-plugins/docker-compose version"
