- name: Check if certificates already exists
  ansible.builtin.stat:
    path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
  register: cert_file

- name: Obtain a TLS certificate with Certbot (only if they don't exist)
  ansible.builtin.command: certbot --nginx --agree-tos --non-interactive --email {{ email_address }} -d {{ domain_name }}
  when: not cert_file.stat.exists
  notify:
    - Reload Nginx
