- name: Generate Nginx configuration file
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/etc/nginx/nginx.conf" # /etc/nginx/sites-available/default
    owner: "{{ ansible_user_name }}"
    group: "{{ ansible_user_name }}"
    mode: '0755'

- name: Test Nginx configuration
  ansible.builtin.command: nginx -t

- name: Restart Nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

#  - name: Configure Nginx
#  template:
#    src: default.conf.j2
#    dest:

