# SPDX-License-Identifier: MIT-0
---
# tasks file for api-setup

## docker compose

- name: Start containers with Docker Compose
  ansible.builtin.import_tasks:
    file: docker_compose.yml

## nginx

- name: Install Nginx
  ansible.builtin.import_tasks:
    file: install_nginx.yml

- name: Generate Nginx configuration
  ansible.builtin.import_tasks:
    file: configure_nginx.yml

## certbot

- name: Install Certbot
  ansible.builtin.import_tasks:
    file: install_certbot.yml

- name: Set up TLS certificates
  ansible.builtin.import_tasks:
    file: certbot_certificates.yml
