#SPDX-License-Identifier: MIT-0
---
# tasks file for api-setup

- name: Install packages
  package:
    name:
      - sqlite3
      - docker.io
      - docker-compose
    state: present

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Create the Docker group
  group:
    name: docker
    state: present

- name: Add Ansible user to the docker group
  user:
    name: "{{ ansible_user_name }}"
    groups: docker
    append: true
    

- name: Debug app_directory
  debug:
    var: api_directory

- name: Create a directory for the API code
  file:
    path: "{{ api_directory }}"
    state: directory
    mode: '0755'

- name: Fetch the docker-compose.yml from GitHub
  get_url:
    url: https://raw.githubusercontent.com/0xtr1gger/cloud_resume_challenge/refs/heads/main/src/api-server/docker-compose.yml
    dest: "{{ api_directory }}/docker-compose.yml"    

- name: Ensure previous Docker containers are down
  shell: docker-compose -f {{ api_directory }}/docker-compose.yml down

- name: Ensure no containers are left
  shell: docker container prune --force

- name: Start services with docker-compose up
  shell: docker-compose -f {{ api_directory }}/docker-compose.yml up -d 
